name: Update snapshot
on: 
  pull_request:
    types:
      - labeled
jobs:
  update-vrt-snapshot:
    if: contains(github.event.pull_request.labels.*.name, 'update-snapshots')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git config --global user.email "sakamuu.y@gmail.com" 
          git config --global user.name "sakamuuy"
          git switch ${{ github.head_ref }}

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install --global yarn
      - run: yarn install --frozen-lockfile

      - name: build-storybook
        run: yarn build-storybook

      - name: snapshot
        run: yarn snapshot

      - name: update snapshot
        run: yarn update-snapshot

      - run: |
          git add .
          git commit -m 'update snapshot'
          git push origin ${{ github.head_ref }}
