name: VRT
on: pull_request
jobs:
  vrt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install --global yarn
      - run: yarn install --frozen-lockfile

      - name: build-storybook
        run: yarn build-storybook

      - name: snapshot
        run: yarn snapshot

      - name: VRT
        id: vrt
        run: yarn vrt
        continue-on-error: true

      - name: upload report
        uses: actions/upload-artifact@v2
        with:
          name: vrt-report
          path: |
            report.html
            __actual__
            __screenshots__
            __diff__
          retention-days: 5

      - if: ${{ steps.vrt.outcome != 'success' }}
        run: exit 1