name: VRT
on: pull_request
jobs:
  vrt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install --global yarn
      - run: yarn install --frozen-lockfile

      - name: build-storybook
        run: yarn build-storybook

      - name: snapshot
        run: yarn snapshot

      - name: VRT
        id: step-vrt
        run: yarn vrt
        continue-on-error: true

      - name: upload report.html
        uses: actions/upload-artifact@v2
        with:
          name: report.html
          path: report.html
          retention-days: 5

      - name: upload actual
        uses: actions/upload-artifact@v2
        with:
          name: __actual__
          path: __actual__
          retention-days: 5

      - name: upload screenshots
        uses: actions/upload-artifact@v2
        with:
          name: __screenshots__
          path: __screenshots__
          retention-days: 5

      - name: upload diff
        uses: actions/upload-artifact@v2
        with:
          name: __diff__
          path: __diff__
          retention-days: 5